syntax = "proto3";

package exclave.core.transport.internet.quic;
option csharp_namespace = "Exclave.Core.Transport.Internet.Quic";
option go_package = "github.com/exclavenetwork/exclave-core/v5/transport/internet/quic";
option java_package = "com.github.exclavenetwork.exclave.core.transport.internet.quic";
option java_multiple_files = true;

import "google/protobuf/any.proto";
import "common/protocol/headers.proto";

import "common/protoext/extensions.proto";

message Config {
  option (exclave.core.common.protoext.message_opt).type = "transport";
  option (exclave.core.common.protoext.message_opt).short_name = "quic";

  string key = 1;
  exclave.core.common.protocol.SecurityConfig security = 2;
  google.protobuf.Any header = 3;
  optional uint32 connection_id_length = 4;
}
