syntax = "proto3";

package exclave.core.proxy.tuic;
option csharp_namespace = "Exclave.Core.Proxy.Tuic";
option go_package = "github.com/exclavenetwork/exclave-core/v5/proxy/tuic";
option java_package = "com.github.exclavenetwork.exclave.core.proxy.tuic";
option java_multiple_files = true;

import "common/protoext/extensions.proto";
import "common/net/address.proto";

message ClientConfig {
  option (exclave.core.common.protoext.message_opt).type = "outbound";
  option (exclave.core.common.protoext.message_opt).short_name = "tuic";

  exclave.core.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  string uuid = 3;
  string password = 4;
  string congestion_control = 5;
  string udp_relay_mode = 6;
  bool zero_rtt_handshake = 7;
  uint32 heartbeat = 8;
  bool udp_over_stream = 9;
  reserved 10;
}

message ServerConfig {
  option (exclave.core.common.protoext.message_opt).type = "inbound";
  option (exclave.core.common.protoext.message_opt).short_name = "tuic";

  exclave.core.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  string uuid = 3;
  string password = 4;
  string congestion_control = 5;
  string udp_relay_mode = 6;
  uint32 heartbeat = 7;
  bool udp_over_stream = 8;
}
