syntax = "proto3";

package exclave.core.proxy.http;
option csharp_namespace = "Exclave.Core.Proxy.Http";
option go_package = "github.com/exclavenetwork/exclave-core/v5/proxy/http";
option java_package = "com.github.exclavenetwork.exclave.core.proxy.http";
option java_multiple_files = true;

import "common/protocol/server_spec.proto";

message Account {
  string username = 1;
  string password = 2;
  map<string,string> headers = 3;
}

// Config for HTTP proxy server.
message ServerConfig {
  reserved 1;
  map<string, string> accounts = 2;
  bool allow_transparent = 3;
  uint32 user_level = 4;
}

// ClientConfig is the protobuf config for HTTP proxy client.
message ClientConfig {
  // Sever is a list of HTTP server addresses.
  repeated exclave.core.common.protocol.ServerEndpoint server = 1;
  bool h1_skip_wait_for_reply = 2;
  bool connect_udp = 3;
  string uri_template = 4;
}
