syntax = "proto3";

package exclave.core.proxy.mieru;
option csharp_namespace = "Exclave.Core.Proxy.Mieru";
option go_package = "github.com/exclavenetwork/exclave-core/v5/proxy/mieru";
option java_package = "com.github.exclavenetwork.exclave.core.proxy.mieru";
option java_multiple_files = true;

import "common/protoext/extensions.proto";
import "common/net/address.proto";

message ClientConfig {
  option (exclave.core.common.protoext.message_opt).type = "outbound";
  option (exclave.core.common.protoext.message_opt).short_name = "mieru";

  exclave.core.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  repeated string port_range = 3;
  string username = 4;
  string password = 5;
  string protocol = 6;
  string multiplexing = 7;
  string handshake_mode = 8;
  string traffic_pattern = 9;
}

message ServerConfig {
  option (exclave.core.common.protoext.message_opt).type = "inbound";
  option (exclave.core.common.protoext.message_opt).short_name = "mieru";

  exclave.core.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  repeated string port_range = 3;
  string username = 4;
  string password = 5;
  string protocol = 6;
  string multiplexing = 7;
  string handshake_mode = 8;
  string traffic_pattern = 9;
}
