syntax = "proto3";

package exclave.core.proxy.http3;
option csharp_namespace = "Exclave.Core.Proxy.Http3";
option go_package = "github.com/exclavenetwork/exclave-core/v5/proxy/http3";
option java_package = "com.github.exclavenetwork.exclave.core.proxy.http3";
option java_multiple_files = true;

import "common/net/address.proto";
import "common/protoext/extensions.proto";

message ClientConfig {
  option (exclave.core.common.protoext.message_opt).type = "outbound";
  option (exclave.core.common.protoext.message_opt).short_name = "http3";

  exclave.core.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  uint32 level = 3;
  optional string username = 4;
  optional string password = 5;
  map<string,string> headers = 6;
  bool connect_udp = 7;
  string uri_template = 8;
}
