// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proxy/shadowquic/config.proto

package shadowquic

import (
	net "github.com/exclavenetwork/exclave-core/v5/common/net"
	_ "github.com/exclavenetwork/exclave-core/v5/common/protoext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Address           *net.IPOrDomain        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port              uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password          string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CongestionControl string                 `protobuf:"bytes,5,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	UdpOverStream     bool                   `protobuf:"varint,6,opt,name=udp_over_stream,json=udpOverStream,proto3" json:"udp_over_stream,omitempty"`
	ZeroRttHandshake  bool                   `protobuf:"varint,7,opt,name=zero_rtt_handshake,json=zeroRttHandshake,proto3" json:"zero_rtt_handshake,omitempty"`
	ServerName        string                 `protobuf:"bytes,8,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Alpn              []string               `protobuf:"bytes,9,rep,name=alpn,proto3" json:"alpn,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_shadowquic_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_shadowquic_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_shadowquic_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetAddress() *net.IPOrDomain {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ClientConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ClientConfig) GetUdpOverStream() bool {
	if x != nil {
		return x.UdpOverStream
	}
	return false
}

func (x *ClientConfig) GetZeroRttHandshake() bool {
	if x != nil {
		return x.ZeroRttHandshake
	}
	return false
}

func (x *ClientConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ClientConfig) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

type ServerConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Address           *net.IPOrDomain        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port              uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password          string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CongestionControl string                 `protobuf:"bytes,5,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	UdpOverStream     bool                   `protobuf:"varint,6,opt,name=udp_over_stream,json=udpOverStream,proto3" json:"udp_over_stream,omitempty"`
	ServerName        string                 `protobuf:"bytes,7,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Alpn              []string               `protobuf:"bytes,8,rep,name=alpn,proto3" json:"alpn,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_shadowquic_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_shadowquic_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_shadowquic_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetAddress() *net.IPOrDomain {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ServerConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ServerConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ServerConfig) GetUdpOverStream() bool {
	if x != nil {
		return x.UdpOverStream
	}
	return false
}

func (x *ServerConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerConfig) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

var File_proxy_shadowquic_config_proto protoreflect.FileDescriptor

const file_proxy_shadowquic_config_proto_rawDesc = "" +
	"\n" +
	"\x1dproxy/shadowquic/config.proto\x12\x1dexclave.core.proxy.shadowquic\x1a common/protoext/extensions.proto\x1a\x18common/net/address.proto\"\xef\x02\n" +
	"\fClientConfig\x12=\n" +
	"\aaddress\x18\x01 \x01(\v2#.exclave.core.common.net.IPOrDomainR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12-\n" +
	"\x12congestion_control\x18\x05 \x01(\tR\x11congestionControl\x12&\n" +
	"\x0fudp_over_stream\x18\x06 \x01(\bR\rudpOverStream\x12,\n" +
	"\x12zero_rtt_handshake\x18\a \x01(\bR\x10zeroRttHandshake\x12\x1f\n" +
	"\vserver_name\x18\b \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04alpn\x18\t \x03(\tR\x04alpn:\x1a\x82\xb5\x18\x16\n" +
	"\boutbound\x12\n" +
	"shadowquic\"\xc0\x02\n" +
	"\fServerConfig\x12=\n" +
	"\aaddress\x18\x01 \x01(\v2#.exclave.core.common.net.IPOrDomainR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12-\n" +
	"\x12congestion_control\x18\x05 \x01(\tR\x11congestionControl\x12&\n" +
	"\x0fudp_over_stream\x18\x06 \x01(\bR\rudpOverStream\x12\x1f\n" +
	"\vserver_name\x18\a \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04alpn\x18\b \x03(\tR\x04alpn:\x19\x82\xb5\x18\x15\n" +
	"\ainbound\x12\n" +
	"shadowquicB\x97\x01\n" +
	"7com.github.exclavenetwork.exclave.core.proxy.shadowquicP\x01Z:github.com/exclavenetwork/exclave-core/v5/proxy/shadowquic\xaa\x02\x1dExclave.Core.Proxy.Shadowquicb\x06proto3"

var (
	file_proxy_shadowquic_config_proto_rawDescOnce sync.Once
	file_proxy_shadowquic_config_proto_rawDescData []byte
)

func file_proxy_shadowquic_config_proto_rawDescGZIP() []byte {
	file_proxy_shadowquic_config_proto_rawDescOnce.Do(func() {
		file_proxy_shadowquic_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_shadowquic_config_proto_rawDesc), len(file_proxy_shadowquic_config_proto_rawDesc)))
	})
	return file_proxy_shadowquic_config_proto_rawDescData
}

var file_proxy_shadowquic_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_shadowquic_config_proto_goTypes = []any{
	(*ClientConfig)(nil),   // 0: exclave.core.proxy.shadowquic.ClientConfig
	(*ServerConfig)(nil),   // 1: exclave.core.proxy.shadowquic.ServerConfig
	(*net.IPOrDomain)(nil), // 2: exclave.core.common.net.IPOrDomain
}
var file_proxy_shadowquic_config_proto_depIdxs = []int32{
	2, // 0: exclave.core.proxy.shadowquic.ClientConfig.address:type_name -> exclave.core.common.net.IPOrDomain
	2, // 1: exclave.core.proxy.shadowquic.ServerConfig.address:type_name -> exclave.core.common.net.IPOrDomain
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_shadowquic_config_proto_init() }
func file_proxy_shadowquic_config_proto_init() {
	if File_proxy_shadowquic_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_shadowquic_config_proto_rawDesc), len(file_proxy_shadowquic_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_shadowquic_config_proto_goTypes,
		DependencyIndexes: file_proxy_shadowquic_config_proto_depIdxs,
		MessageInfos:      file_proxy_shadowquic_config_proto_msgTypes,
	}.Build()
	File_proxy_shadowquic_config_proto = out.File
	file_proxy_shadowquic_config_proto_goTypes = nil
	file_proxy_shadowquic_config_proto_depIdxs = nil
}
